project:
  type: website

website:
  title: "GenCounter"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: functions.qmd
        text: Functions

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



